#!/usr/bin/env python3
"""
dlna_library_ddl_index.py — The INDEX half of the schema — everything `clear(udn)` owns and a
rebuild recreates from the files on disk: `tracks`, its FTS5 shadow
table and sync triggers, the per-root file cache and the crawl
timestamps.

This is the half that is DERIVED. Every row here can be regenerated by
re-reading the music; nothing here is authored. That is exactly why it
is separated from `..._user.py`, whose rows cannot be regenerated by
anything.

Split out of `dlna_library_ddl.py` on 2026-09-20, which had
reached 399 of its 400-line budget. No logic, no imports —
literal DDL as DATA, concatenated by `dlna_library_ddl.SCHEMA_DDL`.
After ANY change here run `python3 tools/regen_schema.py`.
"""
from __future__ import annotations

SCHEMA_INDEX = """

                -- bit_depth + sample_rate are parsed from the URL by
                -- _parse_audio_params (AssetUPnP pattern /b<NN>/f<MMMMM>/).
                -- They participate in the UNIQUE so a 16-bit and 24-bit
                -- copy of the same (artist, album, title) coexist as
                -- distinct rows — the gateway's browse-side filter then
                -- shows only the higher-quality winner in browse listings.
                -- For non-AssetUPnP MediaServers that don't encode these
                -- in the URL, both columns stay NULL; SQLite treats NULLs
                -- as distinct in UNIQUE, so such tracks don't collide
                -- with each other either.
                -- album_key (the LocalFs FOLDER identity) joined the UNIQUE
                -- 2026-07-12: two DISTINCT files in different folders with
                -- identical tags (duplicate editions, scene comps sharing
                -- tag tuples) are both real and both indexable. UPnP rows
                -- keep album_key='' so their dedup semantics are unchanged.
                CREATE TABLE IF NOT EXISTS tracks (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    udn         TEXT NOT NULL,
                    obj_id      TEXT,
                    url         TEXT NOT NULL,
                    title       TEXT,
                    artist      TEXT,
                    album       TEXT,
                    duration    TEXT,
                    art         TEXT,
                    mime        TEXT,
                    genre       TEXT DEFAULT '',
                    file_path   TEXT DEFAULT '',
                    bit_depth   INTEGER,
                    sample_rate INTEGER,
                    year        INTEGER,    -- file-tag year (DIDL-Lite dc:date)
                    album_key   TEXT DEFAULT '',
                    -- Credits, read from the file tags (2026-09-20).
                    -- Deliberately NOT in the UNIQUE below: they
                    -- describe who WROTE the song, so two rows that
                    -- differ only by composer are a retag of one file,
                    -- not two tracks.
                    composer    TEXT DEFAULT '',
                    lyricist    TEXT DEFAULT '',
                    UNIQUE(udn, artist, album, title, album_key, bit_depth, sample_rate)
                );
                CREATE TABLE IF NOT EXISTS index_meta (
                    udn        TEXT PRIMARY KEY,
                    indexed_at TEXT
                );
                -- LocalFs scanner's per-file cache (Phase 2 of the AssetUPnP
                -- migration). Lets incremental rescans skip unchanged files.
                -- Path is the absolute path on disk. Stable obj_id is
                -- sha1(rel_path)[:16] — survives renumbering across rescans
                -- the way AssetUPnP's d-id never did.
                CREATE TABLE IF NOT EXISTS localfs_files (
                    path         TEXT PRIMARY KEY,
                    mtime        REAL    NOT NULL,
                    size         INTEGER NOT NULL,
                    track_id     TEXT    NOT NULL,
                    last_scanned INTEGER NOT NULL
                );
                -- URL uniqueness per UDN is enforced by
                -- idx_tracks_udn_url, but the CREATE INDEX is run by
                -- `_migrate_unique_url` (which first dedupes existing
                -- rows) NOT here — putting it in execute_script would
                -- fail on existing DBs with pre-fix dupes.
                CREATE VIRTUAL TABLE IF NOT EXISTS tracks_fts USING fts5(
                    title, artist, album,
                    content=tracks, content_rowid=id,
                    tokenize='unicode61 remove_diacritics 1'
                );
                -- Migration: add genre column to existing DBs
                -- (no-op if column already exists)
                CREATE TRIGGER IF NOT EXISTS tracks_ai
                    AFTER INSERT ON tracks BEGIN
                        INSERT INTO tracks_fts(rowid, title, artist, album)
                        VALUES (new.id, new.title, new.artist, new.album);
                    END;
                CREATE TRIGGER IF NOT EXISTS tracks_ad
                    AFTER DELETE ON tracks BEGIN
                        INSERT INTO tracks_fts(tracks_fts, rowid, title, artist, album)
                        VALUES ('delete', old.id, old.title, old.artist, old.album);
                    END;
"""
