#!/usr/bin/env python3
"""
tools/badges.py — regenerate the badge strip at the top of README.md.

The numbers in those badges were typed by hand, which is fine right up
until somebody adds a test. A number nobody verifies is worse than no
number at all, because a reader believes it.

So the strip is rendered from the suites themselves, and the suites
check it back:

  * `tests/test_badges.py` verifies the **unit** and **browser** counts.
    Both are collected without running anything, so it costs ~0.3s and
    rides along in `run_all.py` like any other unit test.
  * `run_all.py` verifies the **checks** count itself, at the end of an
    `--offline` run, using the total it has just finished counting. That
    one cannot live in a unit test: the only way to know how many checks
    `run_all.py` performs is to perform them, and a unit test that ran
    the runner would recurse into itself.

    python3 tools/badges.py            # report, change nothing (exit 1 if stale)
    python3 tools/badges.py --write    # rewrite the strip
"""
import re
import subprocess
import sys
import unittest
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
README = PROJECT / "README.md"

# The strip lives between these markers, so this tool touches nothing
# else in the file and a human can move it without breaking the writer.
BEGIN = "<!-- badges: generated by tools/badges.py -->"
END = "<!-- /badges -->"

SHIELDS = "https://img.shields.io/badge"


class CountError(RuntimeError):
    """A suite could not be counted, and why."""


def count_unit():
    """Behavioural unit tests, discovered but not run."""
    suite = unittest.defaultTestLoader.discover(str(PROJECT / "tests"),
                                                top_level_dir=str(PROJECT))
    if getattr(unittest.defaultTestLoader, "errors", None):
        raise CountError(f"discovery failed: {unittest.defaultTestLoader.errors[0]}")
    return _size(suite)


def _size(suite):
    return sum(_size(item) if isinstance(item, unittest.TestSuite) else 1
               for item in suite)


def count_browser():
    """The Playwright suite, collected but not run."""
    out = _run([sys.executable, "-m", "pytest", "tests/frontend",
                "--collect-only", "-q", "-p", "no:warnings"], "pytest")
    found = re.search(r"^(\d+) tests? collected", out, re.MULTILINE)
    if not found:
        raise CountError("pytest collected no frontend tests")
    return int(found.group(1))


def count_checks():
    """`run_all.py --offline`, in full. Takes about a minute — the check
    count is what the runner *does*, so the only way to know it is to let
    it do it. This is why --write is a deliberate command and not a gate.
    """
    out = _run([sys.executable, "tests/run_all.py", "--offline"], "run_all.py")
    # Both outcomes carry the total, and we want the count either way:
    # while the strip is stale the badge gate itself fails, so insisting
    # on a green run would make the tool unable to fix the very thing
    # that is failing.
    found = (re.search(r"ALL (\d+) TESTS PASSED", out)
             or re.search(r"FAILED: \d+/(\d+) test", out))
    if not found:
        raise CountError("run_all.py --offline printed no summary at all")
    return int(found.group(1))


def _run(argv, what):
    try:
        result = subprocess.run(argv, cwd=PROJECT, capture_output=True,
                                text=True, timeout=900, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise CountError(f"could not run {what}: {exc}") from exc
    return result.stdout + result.stderr


def quote(text):
    """shields.io URL-escaping. `-` and `_` are its own field separators
    and must be doubled rather than percent-encoded, or the label splits
    into a second colour field and the badge renders wrong.
    """
    return (text.replace("-", "--").replace("_", "__")
                .replace(" ", "%20").replace("·", "%C2%B7")
                .replace(",", "%2C").replace("+", "%2B"))


def _badge(alt, slug, link):
    return f"[![{alt}]({SHIELDS}/{slug}.svg)]({link})"


def render(checks, unit, browser, gates=5):
    tests = quote(f"{checks} checks · {unit:,} unit · {browser} browser")
    return "\n".join([
        BEGIN,
        _badge("License: MIT", "License-MIT-blue", "LICENSE"),
        _badge("Python 3.14+", "python-3.14%2B-blue", "https://www.python.org/"),
        _badge("Tests", f"tests-{tests}-brightgreen", "#testing"),
        _badge("Lint: ruff", "lint-ruff%20%C2%B7%200%20violations-brightgreen",
               "#code-quality-gates"),
        # Label and message are quoted SEPARATELY: the `-` between them is
        # shields.io's own field separator and must stay single, while any
        # `-` inside either half has to be doubled.
        _badge("Quality gates",
               f"{quote('quality gates')}-{quote(f'{gates} · all at zero')}"
               f"-brightgreen",
               "#code-quality-gates"),
        _badge("Security policy", "security-policy-informational", "SECURITY.md"),
        END,
    ])


def current_strip():
    text = README.read_text()
    start, end = text.find(BEGIN), text.find(END)
    if start == -1 or end == -1:
        raise CountError(f"README.md has no badge markers; add {BEGIN} and {END}")
    return text[start:end + len(END)]


def write_strip(strip):
    """Returns whether anything changed."""
    current = current_strip()
    if current == strip:
        return False
    README.write_text(README.read_text().replace(current, strip, 1))
    return True


def main(argv):
    strip = render(count_checks(), count_unit(), count_browser())
    if "--write" in argv:
        print("Badges updated." if write_strip(strip)
              else "Badges were already right.")
        return 0
    if current_strip() == strip:
        print("Badges are current.")
        return 0
    print("Badges are STALE — run: python3 tools/badges.py --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
